version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresQl
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgresData

volumes:
  postgres_data:
